using System.Text.Json.Serialization;

namespace Sockseek.Api;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ServerInfoDto))]
[JsonSerializable(typeof(ServerStatusDto))]
[JsonSerializable(typeof(SoulseekClientStatusDto))]
[JsonSerializable(typeof(ProfileSummaryDto))]
[JsonSerializable(typeof(ApiErrorDto))]
[JsonSerializable(typeof(CancelWorkflowResponseDto))]
[JsonSerializable(typeof(ResourceActionDto))]
[JsonSerializable(typeof(JobSummaryDto))]
[JsonSerializable(typeof(JobDetailDto))]
[JsonSerializable(typeof(WorkflowSummaryDto))]
[JsonSerializable(typeof(WorkflowDetailDto))]
[JsonSerializable(typeof(WorkflowJobNodeDto))]
[JsonSerializable(typeof(WorkflowTreeDto))]
[JsonSerializable(typeof(JobQuery))]
[JsonSerializable(typeof(ServerJobKind))]
[JsonSerializable(typeof(ServerJobState))]
[JsonSerializable(typeof(ServerWorkflowState))]
[JsonSerializable(typeof(ServerFailureReason))]
[JsonSerializable(typeof(ServerFolderRetrievalOutcome))]
[JsonSerializable(typeof(ServerResourceActionKind))]

[JsonSerializable(typeof(SubmitExtractJobRequestDto))]
[JsonSerializable(typeof(SubmitSearchJobRequestDto))]
[JsonSerializable(typeof(SubmitTrackSearchJobRequestDto))]
[JsonSerializable(typeof(SubmitAlbumSearchJobRequestDto))]
[JsonSerializable(typeof(SubmitSongJobRequestDto))]
[JsonSerializable(typeof(SubmitAlbumJobRequestDto))]
[JsonSerializable(typeof(SubmitAggregateJobRequestDto))]
[JsonSerializable(typeof(SubmitAlbumAggregateJobRequestDto))]
[JsonSerializable(typeof(SubmitJobListRequestDto))]
[JsonSerializable(typeof(RetrieveFolderRequestDto))]
[JsonSerializable(typeof(StartFileDownloadsRequestDto))]
[JsonSerializable(typeof(StartFolderDownloadRequestDto))]
[JsonSerializable(typeof(FileSearchProjectionRequestDto))]
[JsonSerializable(typeof(FolderSearchProjectionRequestDto))]
[JsonSerializable(typeof(AggregateTrackProjectionRequestDto))]
[JsonSerializable(typeof(AggregateAlbumProjectionRequestDto))]
[JsonSerializable(typeof(SubmissionOptionsDto))]
[JsonSerializable(typeof(DownloadBehaviorPolicyDto))]
[JsonSerializable(typeof(Sockseek.Core.DownloadBehavior))]

[JsonSerializable(typeof(JobDraftDto))]
[JsonSerializable(typeof(ExtractJobDraftDto))]
[JsonSerializable(typeof(TrackSearchJobDraftDto))]
[JsonSerializable(typeof(AlbumSearchJobDraftDto))]
[JsonSerializable(typeof(SongJobDraftDto))]
[JsonSerializable(typeof(AlbumJobDraftDto))]
[JsonSerializable(typeof(AggregateJobDraftDto))]
[JsonSerializable(typeof(AlbumAggregateJobDraftDto))]
[JsonSerializable(typeof(JobListJobDraftDto))]

[JsonSerializable(typeof(JobPayloadDto))]
[JsonSerializable(typeof(ExtractJobPayloadDto))]
[JsonSerializable(typeof(SearchJobPayloadDto))]
[JsonSerializable(typeof(SongJobPayloadDto))]
[JsonSerializable(typeof(AlbumJobPayloadDto))]
[JsonSerializable(typeof(AggregateJobPayloadDto))]
[JsonSerializable(typeof(AlbumAggregateJobPayloadDto))]
[JsonSerializable(typeof(JobListPayloadDto))]
[JsonSerializable(typeof(RetrieveFolderJobPayloadDto))]
[JsonSerializable(typeof(GenericJobPayloadDto))]

[JsonSerializable(typeof(SongQueryDto))]
[JsonSerializable(typeof(AlbumQueryDto))]
[JsonSerializable(typeof(FileCandidateRefDto))]
[JsonSerializable(typeof(AlbumFolderRefDto))]
[JsonSerializable(typeof(PeerInfoDto))]
[JsonSerializable(typeof(SearchRawResultDto))]
[JsonSerializable(typeof(SearchResultSnapshotDto<FileCandidateDto>))]
[JsonSerializable(typeof(SearchResultSnapshotDto<AlbumFolderDto>))]
[JsonSerializable(typeof(SearchResultSnapshotDto<AggregateTrackCandidateDto>))]
[JsonSerializable(typeof(SearchResultSnapshotDto<AggregateAlbumCandidateDto>))]
[JsonSerializable(typeof(FileCandidateDto))]
[JsonSerializable(typeof(AlbumFolderDto))]
[JsonSerializable(typeof(AggregateTrackCandidateDto))]
[JsonSerializable(typeof(AggregateAlbumCandidateDto))]
[JsonSerializable(typeof(FileAttributeDto))]

[JsonSerializable(typeof(DownloadSettingsPatchDto))]
[JsonSerializable(typeof(OutputSettingsPatchDto))]
[JsonSerializable(typeof(SearchSettingsPatchDto))]
[JsonSerializable(typeof(FileConditionsPatchDto))]
[JsonSerializable(typeof(FolderConditionsPatchDto))]
[JsonSerializable(typeof(SkipSettingsPatchDto))]
[JsonSerializable(typeof(PreprocessSettingsPatchDto))]
[JsonSerializable(typeof(ExtractionSettingsPatchDto))]
[JsonSerializable(typeof(TransferSettingsPatchDto))]
[JsonSerializable(typeof(SpotifySettingsPatchDto))]
[JsonSerializable(typeof(YouTubeSettingsPatchDto))]
[JsonSerializable(typeof(YtDlpSettingsPatchDto))]
[JsonSerializable(typeof(CsvSettingsPatchDto))]
[JsonSerializable(typeof(BandcampSettingsPatchDto))]
[JsonSerializable(typeof(CollectionPatchDto<string>))]
[JsonSerializable(typeof(CollectionPatchDto<RegexRuleDto>))]

[JsonSerializable(typeof(DownloadSettingsDeltaDto))]
[JsonSerializable(typeof(DownloadSettingOperationDto))]
[JsonSerializable(typeof(RegexRuleDto))]
[JsonSerializable(typeof(RegexFieldsDto))]

[JsonSerializable(typeof(ServerEventEnvelopeDto))]
[JsonSerializable(typeof(ServerEventDescriptorDto))]
[JsonSerializable(typeof(SearchUpdatedDto))]
[JsonSerializable(typeof(ExtractionStartedEventDto))]
[JsonSerializable(typeof(ExtractionFailedEventDto))]
[JsonSerializable(typeof(JobStartedEventDto))]
[JsonSerializable(typeof(JobStatusEventDto))]
[JsonSerializable(typeof(SongSearchingEventDto))]
[JsonSerializable(typeof(DownloadStartedEventDto))]
[JsonSerializable(typeof(DownloadProgressEventDto))]
[JsonSerializable(typeof(DownloadStateChangedEventDto))]
[JsonSerializable(typeof(DownloadAttemptFailedEventDto))]
[JsonSerializable(typeof(SongStateChangedEventDto))]
[JsonSerializable(typeof(AlbumDownloadStartedEventDto))]
[JsonSerializable(typeof(AlbumTrackDownloadStartedEventDto))]
[JsonSerializable(typeof(AlbumDownloadCompletedEventDto))]
[JsonSerializable(typeof(SearchRateLimitedEventDto))]
[JsonSerializable(typeof(SearchResumedEventDto))]
[JsonSerializable(typeof(JobFolderRetrievingEventDto))]
[JsonSerializable(typeof(OnCompleteStartedEventDto))]
[JsonSerializable(typeof(OnCompleteEndedEventDto))]
[JsonSerializable(typeof(TrackBatchResolvedEventDto))]

[JsonSerializable(typeof(IReadOnlyList<ProfileSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<ServerEventDescriptorDto>))]
[JsonSerializable(typeof(IReadOnlyList<JobSummaryDto>))]
[JsonSerializable(typeof(IReadOnlyList<ResourceActionDto>))]
[JsonSerializable(typeof(IReadOnlyList<FileCandidateDto>))]
[JsonSerializable(typeof(IReadOnlyList<AlbumFolderDto>))]
[JsonSerializable(typeof(IReadOnlyList<AggregateTrackCandidateDto>))]
[JsonSerializable(typeof(IReadOnlyList<AggregateAlbumCandidateDto>))]
[JsonSerializable(typeof(IReadOnlyList<SongJobPayloadDto>))]
[JsonSerializable(typeof(IReadOnlyList<JobDraftDto>))]
[JsonSerializable(typeof(IReadOnlyList<FileCandidateRefDto>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, bool>))]
public partial class SockseekApiJsonContext : JsonSerializerContext;
